DEVICE_HOST := "remarkable"

build:
        cargo build --release --target=armv7-unknown-linux-gnueabihf

calculator:
        cargo build --release --target=armv7-unknown-linux-gnueabihf --example calculator

deploy-calculator:
	ssh {{DEVICE_HOST}} 'killall -q -9 calculator || true; systemctl stop xochitl || true'
	scp ../target/armv7-unknown-linux-gnueabihf/release/examples/calculator {{DEVICE_HOST}}:
	ssh {{DEVICE_HOST}} 'RUST_BACKTRACE=1 RUST_LOG=debug ./calculator'
